import { PostgresSocialRepository } from '../../infrastructure/database/PostgresSocialRepository.js';
import { Follow, Interaction, TargetType, InteractionTargetType, ReactionType } from '../../domain/entities/index.js';
import { publishSocialEvent } from '../../infrastructure/messaging/publisher.js';
import { FollowEvent, UnfollowEvent, InteractionEvent } from '../../domain/events/SocialEvents.js';

export class SocialService {
  constructor(private repo: PostgresSocialRepository) { }

  // --- Graph ---
  async followUser(followerId: string, targetUserId: string) {
    if (followerId === targetUserId) throw new Error('Cannot follow self');
    const follow = Follow.create(followerId, targetUserId, 'USER');
    await this.repo.createFollow(follow);

    // Publish
    try {
      await publishSocialEvent(new FollowEvent({
        followerId,
        followingId: targetUserId,
        targetType: 'USER'
      }));
    } catch (err) {
      console.error('Failed to publish follow event:', err);
    }
  }

  async unfollowUser(followerId: string, targetUserId: string) {
    await this.repo.removeFollow(followerId, targetUserId, 'USER');

    await publishSocialEvent(new UnfollowEvent({
      followerId,
      followingId: targetUserId,
      targetType: 'USER'
    }));
  }

  async getFollowers(userId: string, limit = 20, offset = 0) {
    return await this.repo.getFollowers(userId, 'USER', limit, offset);
  }

  // --- Interactions ---
  async reactToEntity(userId: string, targetId: string, targetType: InteractionTargetType, type: ReactionType = 'LIKE') {
    // TODO: Validate targetId exists externally (Phase 0 Check)
    const interaction = new Interaction('', userId, targetId, targetType, type, new Date());
    await this.repo.addInteraction(interaction);

    await publishSocialEvent(new InteractionEvent({
      id: interaction.id, // Note: ID might be empty string if generated by DB? 
      // PostgresSocialRepository inserts using gen_random_uuid() so we don't know the ID unless we return it.
      // But for Feed, userId+targetId is usually enough.
      userId,
      targetId,
      targetType,
      interactionType: type
    }));
  }

  async unreactToEntity(userId: string, targetId: string, targetType: InteractionTargetType) {
    await this.repo.removeInteraction(userId, targetId, targetType, 'LIKE');
  }
}
